
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_adtech
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adtech
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  etl:
    build: ./etl
    depends_on:
      - mysql

volumes:
  mysql_data:
