version: '3.8'
services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=ad_platform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ad_platform
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: 